version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ORG_NAME=Komunitas Kelas Pak Agus
        - ORG_TAGLINE=Belajar Bareng Cloud Computing
        - ORG_MISSION=Menguasai teknologi Docker dan DevOps untuk masa depan.
        - ORG_VISION=Menjadi kelas Sistem Informasi yang paling solutif.
        - ORG_FOUNDED=2026
        - ORG_MEMBERS=35 Anggota
        - ORG_DIVISION=3 Divisi
        - ORG_EMAIL=apiat.abiansyah@tazkia.ac.id
        - ORG_LOCATION=Sentul, Bogor
    container_name: soal-1b-web-container
    ports:
      - "8201:80"
    restart: always
